.PHONY: part1
part1:
	cp -n .templates/chat.* .

.PHONY: part2
part2:
	cp -n .templates/filetransfer.* .

.PHONY: part3
part3:
	cp -n .templates/stopandwait.* .

.PHONY: part4
part4:
	cp -n .templates/gobackn.* .

.PHONY: clean
clean:
	-rm -f $(OBJS) $(PROGRAM)
	rm -rf $(OBJ)
